# Site
name: "DePaul Bioinformatics"
title: "DePaul Bioinformatics"
description: "An online portal for DePaul University Bioinformatics Research Contributions"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
url: https://depaulbioinformatics.github.io
google_analytics: 
disqus: 
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Collections
collections:
  teams:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  members:
    output: true
    permalink: /:collection/:path/
  software:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  jobs:
    output: true
    permalink: /:collection/:path/

all_sections: ["About", "Projects", "Publications", "Software", "Teams", "Members", "Fundings", "Opportunities", "Media"]
all_headers: ["Starting Date", "Ending Date", "Status", "Keyword", "Team", "Member", "Project", "Software", "Publication"]

member_types: ["Principal Investigator", "Faculty", "Postdoctoral Researcher", "PhD Researcher", "Graduate Student", "Undergraduate Student", "External Collaborator", "Alumnus"]
publication_types: ["Publications", "Past Publications"]

default_author_avatar: "assets/images/blank-profile-picture-973460_640.png"

home_page_description: "This is a description of this website... 
Proin massa augue, eleifend non ultricies eget, feugiat ut nisl. Fusce at
aliquet justo, id elementum lacus. Praesent eleifend tempus molestie. Nunc
vulputate sed tortor a ultrices. Nullam blandit hendrerit nisi, at suscipit
augue ultricies quis. Nulla tincidunt rhoncus nisl sed consectetur. Phasellus
dapibus, leo in varius tempus, nibh velit tincidunt lacus, ut porta eros ex et
eros. Ut diam purus, sagittis vitae cursus eu, molestie eget turpis. Sed
consectetur magna in posuere faucibus. Morbi nibh eros, blandit ut vehicula ac,
pellentesque ut urna."


# Defaults
defaults:
  # _teams
  - scope:
      path: ""
      type: teams
    values:
      post_toc: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      post_toc: true
      layout: project
  # _members
  - scope:
      path: ""
      type: members
    values:
      post_toc: true
  # _software
  - scope:
      path: ""
      type: software
    values:
      post_toc: false
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      post_toc: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
